# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-23 16:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nacionalidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'tipo de documento',
                'verbose_name_plural': 'tipos de documento',
            },
        ),
        migrations.RemoveField(
            model_name='donante',
            name='slug',
        ),
        migrations.AddField(
            model_name='donante',
            name='dni',
            field=models.PositiveIntegerField(default=123456789, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='donante',
            name='nacionalidad',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='base.Nacionalidad'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='donante',
            name='tipoDocumento',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='base.TipoDocumento', verbose_name='tipo de documento'),
            preserve_default=False,
        ),
    ]
