# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-29 02:11
from __future__ import unicode_literals

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donante',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to=app.models.establecer_destino_imagen_ubicacion),
        ),
    ]
