# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-24 16:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20160623_1305'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nacionalidad',
            options={'verbose_name_plural': 'nacionalidades'},
        ),
        migrations.RenameField(
            model_name='tipodocumento',
            old_name='nombre',
            new_name='siglas',
        ),
        migrations.AddField(
            model_name='tipodocumento',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
    ]
