# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-01 22:39
from __future__ import unicode_literals

import aplicaciones.base.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20160624_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleregistrodonacion',
            name='fechaHora',
            field=models.DateTimeField(validators=[aplicaciones.base.models.validate_fecha_hora_futuro], verbose_name='fecha y hora'),
        ),
        migrations.AlterField(
            model_name='detalleregistrodonacion',
            name='registro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='base.RegistroDonacion', verbose_name='registro de donación'),
        ),
        migrations.AlterField(
            model_name='registrodonacion',
            name='donante',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='registro', to='base.Donante'),
        ),
    ]
