# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-01 23:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_auto_20160701_2239'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoDonacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'estado de la donación',
                'verbose_name_plural': 'estados de la donación',
            },
        ),
        migrations.CreateModel(
            name='HistoricoEstadoDonacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio', models.DateTimeField()),
                ('fin', models.DateTimeField(blank=True, null=True)),
                ('donacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historicoEstados', to='base.DetalleRegistroDonacion')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.EstadoDonacion')),
            ],
            options={
                'verbose_name': 'histórico de estados de donación',
                'verbose_name_plural': 'históricos de estados de donación',
            },
        ),
        migrations.RemoveField(
            model_name='verificacion',
            name='aceptado',
        ),
    ]
