# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-02 00:53
from __future__ import unicode_literals

import aplicaciones.base.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_auto_20160701_2326'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaHora', models.DateTimeField(validators=[aplicaciones.base.models.validate_fecha_hora_futuro], verbose_name='fecha y hora')),
                ('foto', models.ImageField(blank=True, upload_to='')),
                ('descripcion', models.TextField(blank=True, verbose_name='descripción')),
                ('centroDonacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.CentroDonacion', verbose_name='centro de donación')),
                ('evento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.Evento')),
                ('registro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donaciones', to='base.RegistroDonacion', verbose_name='registro de donación')),
                ('verificacion', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.Verificacion', verbose_name='verificación')),
            ],
            options={
                'verbose_name': 'donación',
                'verbose_name_plural': 'donaciones',
            },
        ),
        migrations.RemoveField(
            model_name='detalleregistrodonacion',
            name='centroDonacion',
        ),
        migrations.RemoveField(
            model_name='detalleregistrodonacion',
            name='evento',
        ),
        migrations.RemoveField(
            model_name='detalleregistrodonacion',
            name='registro',
        ),
        migrations.RemoveField(
            model_name='detalleregistrodonacion',
            name='verificacion',
        ),
        migrations.AlterField(
            model_name='historicoestadodonacion',
            name='donacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historicoEstados', to='base.Donacion'),
        ),
        migrations.DeleteModel(
            name='DetalleRegistroDonacion',
        ),
    ]
