# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-07 21:42
from __future__ import unicode_literals

import aplicaciones.base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_auto_20160702_0053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donacion',
            name='foto',
            field=models.ImageField(blank=True, upload_to=aplicaciones.base.models.establecer_destino_imagen_ubicacion),
        ),
    ]
