# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-17 23:28
from __future__ import unicode_literals

import aplicaciones.base.models
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_auto_20160707_2142'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodigoVerificacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(default=aplicaciones.base.models.obtener_codigo_aleatorio, max_length=12, unique=True)),
                ('fechaVencimiento', models.DateField(default=datetime.date(2016, 8, 16), verbose_name='fecha de vencimiento')),
            ],
            options={
                'verbose_name_plural': 'códigos de verificación',
                'verbose_name': 'código de verificación',
            },
        ),
        migrations.CreateModel(
            name='VerificacionDonacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='')),
            ],
            options={
                'verbose_name_plural': 'verificaciones de donación',
                'verbose_name': 'verificación de donación',
            },
        ),
        migrations.AlterField(
            model_name='donacion',
            name='verificacion',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.VerificacionDonacion', verbose_name='verificación'),
        ),
        migrations.DeleteModel(
            name='Verificacion',
        ),
    ]
