# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-23 21:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_auto_20160718_1404'),
    ]

    operations = [
        migrations.CreateModel(
            name='LugarDonacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Direccion', verbose_name='dirección')),
            ],
            options={
                'verbose_name': 'lugar de donación',
                'verbose_name_plural': 'lugares de donación',
            },
        ),
        migrations.RemoveField(
            model_name='centrodonacion',
            name='direccion',
        ),
        migrations.RemoveField(
            model_name='donacion',
            name='centroDonacion',
        ),
        migrations.RemoveField(
            model_name='evento',
            name='centroDonacion',
        ),
        migrations.AddField(
            model_name='centrodonacion',
            name='lugarDonacion',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='base.LugarDonacion'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='donacion',
            name='lugarDonacion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='base.LugarDonacion', verbose_name='lugar de donación'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='evento',
            name='lugarDonacion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='base.LugarDonacion', verbose_name='lugar de donación'),
            preserve_default=False,
        ),
    ]
