# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-24 20:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_auto_20160723_2121'),
    ]

    operations = [
        migrations.CreateModel(
            name='LugarEvento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'lugar de evento',
                'verbose_name_plural': 'lugares de eventos',
            },
        ),
        migrations.RemoveField(
            model_name='donacion',
            name='evento',
        ),
        migrations.RemoveField(
            model_name='evento',
            name='lugarDonacion',
        ),
        migrations.AlterField(
            model_name='centrodonacion',
            name='lugarDonacion',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lugarCentro', to='base.LugarDonacion'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='evento',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='lugarevento',
            name='evento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lugarEvento', to='base.Evento'),
        ),
        migrations.AddField(
            model_name='lugarevento',
            name='lugarDonacion',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lugarEventoDonacion', to='base.LugarDonacion', verbose_name='lugar de donación'),
        ),
    ]
