# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-25 22:09
from __future__ import unicode_literals

import aplicaciones.base.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_auto_20160724_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donacion',
            name='verificacion',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='donacion', to='base.VerificacionDonacion', verbose_name='verificación'),
        ),
        migrations.AlterField(
            model_name='verificaciondonacion',
            name='imagen',
            field=models.ImageField(upload_to=aplicaciones.base.models.establecer_destino_imagen_ubicacion),
        ),
    ]
