# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-27 12:35
from __future__ import unicode_literals

import aplicaciones.base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_auto_20160725_2209'),
    ]

    operations = [
        migrations.AddField(
            model_name='donante',
            name='claveActivacion',
            field=models.CharField(default=aplicaciones.base.models.obtener_codigo_aleatorio, max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='donante',
            name='vencimientoClaveActivacion',
            field=models.DateTimeField(default=aplicaciones.base.models.fecha_vencimiento_defecto),
        ),
    ]
