# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-31 00:17
from __future__ import unicode_literals

import aplicaciones.base.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import geoposition.fields


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_auto_20160725_2209'),
    ]

    operations = [
        migrations.AddField(
            model_name='direccion',
            name='posicion',
            field=geoposition.fields.GeopositionField(blank=True, max_length=42, null=True, verbose_name='posición'),
        ),
        migrations.AddField(
            model_name='donacion',
            name='estado',
            field=aplicaciones.base.models.SentimientosField(blank=True, choices=[('1', 'Muy mal'), ('2', 'Mal'), ('3', 'Descompuesto'), ('4', 'Bien'), ('5', 'Muy bien'), ('6', 'Excelente')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='horariocentrodonacion',
            name='centro',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='base.CentroDonacion'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='solicituddonacion',
            name='donante',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='base.Donante'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='direccion',
            name='numero',
            field=models.PositiveIntegerField(verbose_name='número'),
        ),
        migrations.AlterField(
            model_name='direccion',
            name='numeroDepartamento',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='número de departamento'),
        ),
        migrations.AlterField(
            model_name='direccion',
            name='piso',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='donante',
            name='direccion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.Direccion', verbose_name='dirección'),
        ),
        migrations.AlterField(
            model_name='donante',
            name='grupoSanguineo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.GrupoSanguineo', verbose_name='grupo sanguíneo'),
        ),
        migrations.AlterField(
            model_name='donante',
            name='numeroDocumento',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True, verbose_name='número de documento'),
        ),
        migrations.AlterField(
            model_name='donante',
            name='telefono',
            field=models.CharField(blank=True, max_length=30, null=True, validators=[django.core.validators.RegexValidator(message='El formato de número de teléfono es incorrecto.', regex='^\\+?[\\d()*-]+$')], verbose_name='teléfono'),
        ),
        migrations.AlterField(
            model_name='donante',
            name='tipoDocumento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.TipoDocumento', verbose_name='tipo de documento'),
        ),
        migrations.AlterField(
            model_name='donante',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='imagensolicituddonacion',
            name='imagen',
            field=models.ImageField(upload_to=aplicaciones.base.models.establecer_destino_imagen_ubicacion),
        ),
        migrations.AlterField(
            model_name='imagensolicituddonacion',
            name='solicitud',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenesSolicitud', to='base.SolicitudDonacion'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='telefono',
            field=models.CharField(blank=True, max_length=30, null=True, validators=[django.core.validators.RegexValidator(message='El formato de número de teléfono es incorrecto.', regex='^\\+?[\\d()*-]+$')], verbose_name='teléfono'),
        ),
        migrations.AlterField(
            model_name='solicituddonacion',
            name='centroDonacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.CentroDonacion', verbose_name='centro de donación'),
        ),
        migrations.AlterField(
            model_name='solicituddonacion',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
