# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-31 01:40
from __future__ import unicode_literals

import aplicaciones.base.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_auto_20160831_0017'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagenevento',
            name='portada',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='imagenevento',
            name='evento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenesEvento', to='base.Evento'),
        ),
        migrations.AlterField(
            model_name='imagenevento',
            name='imagen',
            field=models.ImageField(upload_to=aplicaciones.base.models.establecer_destino_imagen_ubicacion),
        ),
    ]
