# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-01 13:57
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_auto_20160831_0140'),
    ]

    operations = [
        migrations.AddField(
            model_name='centrodonacion',
            name='telefono',
            field=models.CharField(blank=True, max_length=30, null=True, validators=[django.core.validators.RegexValidator(message='El formato de número de teléfono es incorrecto.', regex='^\\+?[\\d()*-]+$')], verbose_name='teléfono'),
        ),
    ]
