# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-31 21:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_auto_20160831_2145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicituddonacion',
            name='fechaHoraInicio',
            field=models.DateField(verbose_name='fecha y hora de inicio'),
        ),
    ]
