# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-20 15:45
from __future__ import unicode_literals

import aplicaciones.base.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_centrodonacion_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donante',
            name='altura',
            field=models.PositiveIntegerField(null=True, validators=[django.core.validators.MinValueValidator(100), django.core.validators.MaxValueValidator(350)]),
        ),
        migrations.AlterField(
            model_name='donante',
            name='genero',
            field=aplicaciones.base.models.GenerosField(choices=[('1', 'Hombre'), ('2', 'Mujer')], max_length=1, null=True, verbose_name='género'),
        ),
        migrations.AlterField(
            model_name='donante',
            name='nacimiento',
            field=models.DateField(null=True, verbose_name='fecha de nacimiento'),
        ),
        migrations.AlterField(
            model_name='donante',
            name='nacionalidad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.Nacionalidad'),
        ),
        migrations.AlterField(
            model_name='donante',
            name='peso',
            field=models.DecimalField(decimal_places=1, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='donante',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='donante', to=settings.AUTH_USER_MODEL),
        ),
    ]
