# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-27 16:55
from __future__ import unicode_literals

import aplicaciones.base.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_auto_20160920_1545'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicituddonacion',
            name='estado',
        ),
        migrations.AddField(
            model_name='imagensolicituddonacion',
            name='portada',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='gruposanguineosolicitud',
            name='solicitud',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gruposSanguineos', to='base.SolicitudDonacion'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='direccion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.Direccion', verbose_name='dirección'),
        ),
        migrations.AlterField(
            model_name='solicituddonacion',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to=aplicaciones.base.models.establecer_destino_imagen_ubicacion),
        ),
        migrations.DeleteModel(
            name='EstadoSolicitudDonacion',
        ),
    ]
