# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-01 17:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_auto_20160831_2145'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicituddonacion',
            name='estado',
        ),
        migrations.AddField(
            model_name='paciente',
            name='numeroDocumento',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True, verbose_name='número de documento'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='tipoDocumento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.TipoDocumento', verbose_name='tipo de documento'),
        ),
        migrations.AlterField(
            model_name='solicituddonacion',
            name='fechaHoraFin',
            field=models.DateTimeField(verbose_name='fecha y hora de fin'),
        ),
        migrations.AlterField(
            model_name='solicituddonacion',
            name='fechaHoraInicio',
            field=models.DateTimeField(verbose_name='fecha y hora de inicio'),
        ),
    ]
