# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-01 18:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_auto_20160901_1717'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='numeroDocumento',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='tipoDocumento',
        ),
        migrations.AlterField(
            model_name='paciente',
            name='direccion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.Direccion', verbose_name='dirección'),
        ),
    ]
