# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-29 12:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_auto_20160927_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicituddonacion',
            name='fechaPublicacion',
            field=models.DateField(auto_now_add=True, verbose_name='fecha de publicación'),
        ),
    ]
