# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-04 10:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_auto_20160901_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicituddonacion',
            name='fechaHoraFin',
            field=models.DateField(verbose_name='fecha y hora de fin'),
        ),
        migrations.AlterField(
            model_name='solicituddonacion',
            name='fechaHoraInicio',
            field=models.DateField(verbose_name='fecha y hora de inicio'),
        ),
    ]
