# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-01 20:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_auto_20160929_1240'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicituddonacion',
            name='historia',
            field=models.TextField(blank=True, null=True),
        ),
    ]
