# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-04 12:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_auto_20160904_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicituddonacion',
            name='fechaPublicacion',
            field=models.DateTimeField(verbose_name='fecha de publicación'),
        ),
    ]
