# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-19 18:12
from __future__ import unicode_literals

import aplicaciones.base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_solicituddonacion_historia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donacion',
            name='verificacion',
        ),
        migrations.AddField(
            model_name='donacion',
            name='imagen_verificacion',
            field=models.ImageField(blank=True, null=True, upload_to=aplicaciones.base.models.establecer_destino_imagen_ubicacion, verbose_name='imagen de verificación'),
        ),
        migrations.AlterField(
            model_name='gruposanguineo',
            name='puedeDonarA',
            field=models.ManyToManyField(blank=True, to='base.GrupoSanguineo', verbose_name='puede donar a'),
        ),
        migrations.DeleteModel(
            name='VerificacionDonacion',
        ),
    ]
