# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-20 18:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_auto_20161019_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicoestadodonacion',
            name='donacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historicoEstados', to='base.Donacion', verbose_name='Historico de Estados'),
        ),
    ]
