# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-04 12:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_auto_20160904_1227'),
    ]

    operations = [
        migrations.RenameField(
            model_name='solicituddonacion',
            old_name='fechaPublicacion',
            new_name='fechaPublicacionSolicitud',
        ),
    ]
