# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-02 12:04
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_auto_20161020_1848'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoriaevento',
            options={'ordering': ['nombre'], 'verbose_name': 'categoría del evento', 'verbose_name_plural': 'categorías del evento'},
        ),
        migrations.AlterModelOptions(
            name='codigoverificacion',
            options={'ordering': ['-fechaEmision'], 'verbose_name': 'código de verificación', 'verbose_name_plural': 'códigos de verificación'},
        ),
        migrations.AlterModelOptions(
            name='donacion',
            options={'ordering': ['-fechaHora'], 'verbose_name': 'donación', 'verbose_name_plural': 'donaciones'},
        ),
        migrations.AlterModelOptions(
            name='estadodonacion',
            options={'ordering': ['nombre'], 'verbose_name': 'estado de la donación', 'verbose_name_plural': 'estados de la donación'},
        ),
        migrations.AlterModelOptions(
            name='evento',
            options={'ordering': ['fechaHoraInicio']},
        ),
        migrations.AlterModelOptions(
            name='gruposanguineo',
            options={'ordering': ['nombre'], 'verbose_name': 'grupo sanguíneo', 'verbose_name_plural': 'grupos sanguíneos'},
        ),
        migrations.AlterModelOptions(
            name='nacionalidad',
            options={'ordering': ['nombre'], 'verbose_name_plural': 'nacionalidades'},
        ),
        migrations.AlterModelOptions(
            name='solicituddonacion',
            options={'ordering': ['-fechaPublicacion'], 'verbose_name': 'solicitud de donación', 'verbose_name_plural': 'solicitudes de donación'},
        ),
        migrations.AlterModelOptions(
            name='tipocentrodonacion',
            options={'ordering': ['nombre'], 'verbose_name': 'tipo de centro de donación', 'verbose_name_plural': 'tipos de centro de donación'},
        ),
        migrations.AlterModelOptions(
            name='tipodocumento',
            options={'ordering': ['siglas'], 'verbose_name': 'tipo de documento', 'verbose_name_plural': 'tipos de documento'},
        ),
        migrations.AlterModelOptions(
            name='tiposolicituddonacion',
            options={'ordering': ['nombre'], 'verbose_name': 'tipo de solicitud de donación', 'verbose_name_plural': 'tipos de solicitud de donación'},
        ),
        migrations.AddField(
            model_name='paciente',
            name='grupoSanguineo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='base.GrupoSanguineo'),
        ),
        migrations.AlterField(
            model_name='donante',
            name='altura',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(100), django.core.validators.MaxValueValidator(350)]),
        ),
        migrations.AlterField(
            model_name='donante',
            name='nacimiento',
            field=models.DateField(blank=True, null=True, verbose_name='fecha de nacimiento'),
        ),
        migrations.AlterField(
            model_name='donante',
            name='nacionalidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.Nacionalidad'),
        ),
        migrations.AlterField(
            model_name='donante',
            name='peso',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
        ),
    ]
