# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-02 13:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0023_auto_20161102_1204'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrodonacion',
            name='privado',
        ),
        migrations.AlterField(
            model_name='solicituddonacion',
            name='centroDonacion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='base.CentroDonacion', verbose_name='centro de donación'),
        ),
    ]
