# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-02 18:32
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0024_auto_20161102_1304'),
    ]

    operations = [
        migrations.AddField(
            model_name='centrodonacion',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='donante',
            name='altura',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(100), django.core.validators.MaxValueValidator(350)], verbose_name='altura en cm.'),
        ),
        migrations.AlterField(
            model_name='donante',
            name='nacionalidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.Nacionalidad'),
        ),
        migrations.AlterField(
            model_name='donante',
            name='peso',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(40), django.core.validators.MaxValueValidator(350)], verbose_name='peso en kg.'),
        ),
        migrations.AlterField(
            model_name='donante',
            name='tipoDocumento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.TipoDocumento', verbose_name='tipo de documento'),
        ),
    ]
