# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-05 00:52
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_donante_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donante',
            name='altura',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(100), django.core.validators.MaxValueValidator(350)]),
        ),
        migrations.AlterField(
            model_name='donante',
            name='telefono',
            field=models.CharField(max_length=20, verbose_name='teléfono'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='telefono',
            field=models.CharField(max_length=20, verbose_name='teléfono'),
        ),
    ]
